services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  identity-service:
    build: ./identity-service
    env_file:
      - ./identity-service/.env
    depends_on:
      identity-db:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  post-service:
    build: ./post-service
    env_file:
      - ./post-service/.env
    depends_on:
      post-db:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  media-service:
    build: ./media-service
    env_file:
      - ./media-service/.env
    depends_on:
      media-db:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  search-service:
    build: ./search-service
    env_file:
      - ./search-service/.env
    depends_on:
      search-db:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  # DATABASES
  identity-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_db
    ports:
      - "5433:5432"
    volumes:
      - identity_db_data:/var/lib/postgresql/data

  post-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_db
    ports:
      - "5434:5432"
    volumes:
      - post_db_data:/var/lib/postgresql/data

  media-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media_db
    ports:
      - "5435:5432"
    volumes:
      - media_db_data:/var/lib/postgresql/data

  search-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: search_db
    ports:
      - "5436:5432"
    volumes:
      - search_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  identity_db_data:
  post_db_data:
  media_db_data:
  search_db_data: